apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hustler-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: hustler-backend
            port:
              number: 8080
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: hustler-frontend
            port:
              number: 80
